---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-reader
rules:
- apiGroups: ["rbac.authorization.k8s.io/v1"]
  resources: ["clusterrolebindings","clusterroles","roles","rolebindings"]
  verbs: ["get","watch","list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: udefreadonlybinding
subjects:
 - kind: ServiceAccount
   name: reader
   namespace: {{ .Release.Namespace }}
roleRef:
   kind: Role
   name: rbac-reader
   apiGroup: rbac.authorization.k8s.io
---
